# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Task < Formula
  desc "A gorgeous, feature-packed drop-in replacement for the go-task project"
  homepage "https://megabyte.space"
  version "11.0.0"
  license "MIT"

  on_macos do
    url "https://github.com/megabyte-labs/go/cli/bodega/releases/download/v11.0.0/bodega_11.0.0_darwin_all.tar.gz"
    sha256 "e02c36295157e0450c110c14bd4f4503e3ba9eba9c76ae07a31a9e9a82a76419"

    def install
      bin.install "task"
      bash_completion.install "completion/bash/task.bash" => "task"
      zsh_completion.install "completion/zsh/_task" => "_task"
      fish_completion.install "completion/fish/task.fish"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/megabyte-labs/go/cli/bodega/releases/download/v11.0.0/bodega_11.0.0_linux_armv6.tar.gz"
      sha256 "e099ccea13704a866490dc23a99322799cb4e004f41cba448c5d9688a303f85f"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/megabyte-labs/go/cli/bodega/releases/download/v11.0.0/bodega_11.0.0_linux_arm64.tar.gz"
      sha256 "be778e42f9c8bbb36ef3df5735fc791a2ad43fdd0d53d3a78a6e0869414ca8b4"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/megabyte-labs/go/cli/bodega/releases/download/v11.0.0/bodega_11.0.0_linux_amd64.tar.gz"
      sha256 "5bdaec06ab58d8ace78c76809e06b524fb66aaf98c905176a81d7dbaac9e9850"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
  end
end
