# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Task < Formula
  desc "A gorgeous, feature-packed drop-in replacement for the go-task project"
  homepage "https://megabyte.space"
  version "11.0.0"
  license "MIT"

  on_macos do
    url "https://github.com/megabyte-labs/go/cli/bodega/releases/download/v11.0.0/bodega_11.0.0_darwin_all.tar.gz"
    sha256 "37066c69071b75b154f7e86426643cb849e3916665260f972273fb4303381028"

    def install
      bin.install "task"
      bash_completion.install "completion/bash/task.bash" => "task"
      zsh_completion.install "completion/zsh/_task" => "_task"
      fish_completion.install "completion/fish/task.fish"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/megabyte-labs/go/cli/bodega/releases/download/v11.0.0/bodega_11.0.0_linux_armv6.tar.gz"
      sha256 "a570f5b28788054449e70fc53e6992224bafb08325b4757c1c58b47c732c1b3d"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/megabyte-labs/go/cli/bodega/releases/download/v11.0.0/bodega_11.0.0_linux_arm64.tar.gz"
      sha256 "3f2a540430e87c4debd8e6c0a87a1f6cb6ce5c4c71475f79d1fbb9d1f266da30"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/megabyte-labs/go/cli/bodega/releases/download/v11.0.0/bodega_11.0.0_linux_amd64.tar.gz"
      sha256 "71745096732fe86a405ea2278030bfa43fd04168674740e66d834f9b892cc6e5"

      def install
        bin.install "task"
        bash_completion.install "completion/bash/task.bash" => "task"
        zsh_completion.install "completion/zsh/_task" => "_task"
        fish_completion.install "completion/fish/task.fish"
      end
    end
  end
end
